### ISSUE TITLE
zig 0.13 compatibility

### ISSUE THREAD

**Issue by balvaldyr** [freakmangd/zentig_ecs#25]
The build.zig is not compatible with zig 0.13

I had a quick look, it's mostly converting lazy paths from `.{ .path = ex_info[1] }` into `b.path(ex_info[1])`.
But the tricky bit will be updating zmath.

**Comment by freakmangd** [comment]
Hi, thanks for the PR. I've added a tag that should work with 0.13.0, the main branch will now target zig master. This should resolve your issue.
